### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by vipsbpig** [CudaText-addons/cuda_fmt_js#1]
When I try to format json file.It print this

Traceback (most recent call last):
  File "D:\Program Files\cudatext\py\cuda_fmt\__init__.py", line 183, in format
    run_format(ed, func, '['+caption+'] ', force_all)
  File "D:\Program Files\cudatext\py\cuda_fmt\fmtrun.py", line 65, in run_format
    text = do_format(text1)
  File "D:\Program Files\cudatext\py\cuda_fmt_js\__init__.py", line 40, in do_format
    return jsbeautifier.beautify(text, options())
  File "D:\Program Files\cudatext\py\cuda_fmt_js\jsbeautifier\__init__.py", line 70, in beautify
    b = Beautifier()
  File "D:\Program Files\cudatext\py\cuda_fmt_js\jsbeautifier\javascript\beautifier.py", line 112, in __init__
    import jsbeautifier.core.acorn as acorn
  File "D:\Program Files\cudatext\py\cuda_fmt_js\jsbeautifier\core\acorn.py", line 16, in <module>
    six = __import__("six")
ModuleNotFoundError: No module named 'six'

**Comment by Alexey-T** [comment]
I added it now; plugin updated in addons, pls test.

**Comment by vipsbpig** [comment]
Sorry for the delay.It works great!
